// ==================== TRANSLATIONS ====================
const translations = {
    it: {
        nav_home: "Home",
        nav_destinations: "Destinazioni",
        nav_tours: "Tour",
        nav_about: "Chi Siamo",
        nav_why: "Perché Noi",
        nav_reviews: "Recensioni",
        nav_contact: "Contatti",
        hero_badge: "Tour Operator Autorizzato",
        hero_title: "Scopri la Campania come non l'hai mai vista",
        hero_subtitle: "Escursioni guidate, sentieri nascosti del Cilento, esperienze enogastronomiche autentiche e le meraviglie di Pompei, Capri e Costiera Amalfitana.",
        hero_cta1: "Esplora i Tour",
        hero_cta2: "Contattaci",
        dest_tag: "Le Nostre Destinazioni",
        dest_title: "Luoghi Incantevoli da Esplorare",
        dest_desc: "Dalle coste mozzafiato ai sentieri segreti del Cilento, ogni destinazione è un'esperienza unica.",
        badge_popular: "Più Richiesto",
        badge_luxury: "Luxury",
        badge_hidden: "Nascosto",
        dest1_title: "Costiera Amalfitana",
        dest1_desc: "Un percorso mozzafiato tra Positano, Amalfi e Ravello, con viste panoramiche sul Mar Tirreno.",
        dest2_title: "Isola di Capri",
        dest2_desc: "Visita la Grotta Azzurra, i Giardini di Augusto e passeggia tra le vie esclusive dell'isola.",
        dest3_title: "Pompei & Vesuvio",
        dest3_desc: "Un viaggio nel tempo tra le rovine antiche e l'ascesa al cratere del vulcano più famoso d'Italia.",
